export enum BankName {
  ABBank = 'ABBank',
  ACB = 'ACB',
  Agribank = 'Agribank',
  BacABank = 'Bac A Bank',
  BaoVietBank = 'Bao Viet Bank',
  BIDV = 'BIDV',
  Cake = 'Cake by VPBank',
  CBBank = 'CBBank',
  Citibank = 'Citibank',
  DongABank = 'Dong A Bank',
  Eximbank = 'Eximbank',
  GPBank = 'GPBank',
  HDBank = 'HDBank',
  HSBC = 'HSBC',
  KienLongBank = 'Kien Long Bank',
  LienVietPostBank = 'LienVietPostBank',
  MBBank = 'MB Bank',
  MSB = 'MSB',
  NamABank = 'Nam A Bank',
  NCB = 'NCB',
  OCB = 'OCB',
  OceanBank = 'OceanBank',
  PublicBank = 'Public Bank',
  PVcomBank = 'PVcomBank',
  SacomBank = 'Sacombank',
  SeABank = 'SeABank',
  SHB = 'SHB',
  Shinhan = 'Shinhan Bank',
  StandardChartered = 'Standard Chartered',
  Techcombank = 'Techcombank',
  Timo = 'Timo',
  TPBank = 'TPBank',
  UOB = 'UOB',
  VIB = 'VIB',
  VietABank = 'VietA Bank',
  VietBank = 'VietBank',
  Vietcombank = 'Vietcombank',
  VietinBank = 'VietinBank',
  VPBank = 'VPBank',
  Woori = 'Woori Bank',
}

export const BankNameOptions = Object.entries(BankName).map(([key, value]) => ({
  label: value,
  value: key,
}));
